import 'property.dart';
import 'project.dart';
import 'lead.dart';

class MockData {
  static final properties = <Property>[
    Property(
      id: 'p1',
      title: 'Greenview Residency Plot',
      type: 'land',
      price: 1800000,
      area: 'Ballarpur Road',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.95,
      lng: 79.29,
      badges: ['Verified', 'Owner'],
      description: 'Corner plot in a gated layout with wide roads and nearby utilities.',
      attrs: {'size': '1800 sqft'},
    ),
    Property(
      id: 'p2',
      title: 'Lakefront Flats Phase 2',
      type: 'flat',
      price: 4200000,
      area: 'Tadoba Road',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.97,
      lng: 79.30,
      badges: ['New'],
      description: 'Modern 2 BHK apartment near schools and shopping.',
      attrs: {'bhk': 2, 'floor': 4},
    ),
    Property(
      id: 'p3',
      title: 'Central Plaza Shop',
      type: 'commercial',
      price: 9500000,
      area: 'Civil Lines',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.96,
      lng: 79.27,
      badges: ['Verified'],
      description: 'Prime retail space with high footfall and parking.',
      attrs: {'size': '900 sqft'},
    ),
    Property(
      id: 'p4',
      title: 'Sunrise Rental Flat',
      type: 'rent',
      price: 18000,
      area: 'Bhadrawati',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.92,
      lng: 79.30,
      badges: ['Ready'],
      description: 'Ready to move 1 BHK with balcony and security.',
      attrs: {'bhk': 1},
    ),
    Property(
      id: 'p5',
      title: 'Orchard View Farm Land',
      type: 'land',
      price: 7800000,
      area: 'Mul Road',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.94,
      lng: 79.33,
      badges: ['Verified'],
      description: 'Fertile land with access to water and main road.',
      attrs: {'acre': '1.5'},
    ),
    Property(
      id: 'p6',
      title: 'Urban Heights 3 BHK',
      type: 'flat',
      price: 6800000,
      area: 'Ghuggus',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.99,
      lng: 79.28,
      badges: ['Owner', 'New'],
      description: 'Spacious 3 BHK with skyline views and amenities.',
      attrs: {'bhk': 3},
    ),
    Property(
      id: 'p7',
      title: 'Market Street Warehouse',
      type: 'commercial',
      price: 12500000,
      area: 'Main Market',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.96,
      lng: 79.31,
      badges: ['Verified'],
      description: 'Large warehouse suitable for logistics and storage.',
      attrs: {'size': '4000 sqft'},
    ),
    Property(
      id: 'p8',
      title: 'Garden Nest Rental',
      type: 'rent',
      price: 24000,
      area: 'Padoli',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.93,
      lng: 79.25,
      badges: ['Ready'],
      description: '2 BHK rental with modular kitchen and parking.',
      attrs: {'bhk': 2},
    ),
    Property(
      id: 'p9',
      title: 'Silver Oaks Villa Plot',
      type: 'land',
      price: 3500000,
      area: 'Ram Nagar',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.98,
      lng: 79.32,
      badges: ['Owner'],
      description: 'Premium villa plot in a quiet neighborhood.',
      attrs: {'size': '2200 sqft'},
    ),
    Property(
      id: 'p10',
      title: 'Riverside Apartments',
      type: 'flat',
      price: 5200000,
      area: 'Nagpur Road',
      citySlug: 'chandrapur',
      coverUrl: null,
      lat: 19.95,
      lng: 79.34,
      badges: ['Verified', 'New'],
      description: 'New launch apartments close to city center.',
      attrs: {'bhk': 2},
    ),
  ];

  static final projects = <Project>[
    Project(
      id: 'pr1',
      name: 'Skyline Heights',
      area: 'Civil Lines',
      status: 'under_construction',
      minPrice: 3800000,
      coverUrl: null,
    ),
    Project(
      id: 'pr2',
      name: 'Emerald Enclave',
      area: 'Tadoba Road',
      status: 'planning',
      minPrice: 3200000,
      coverUrl: null,
    ),
    Project(
      id: 'pr3',
      name: 'Lakeside Avenue',
      area: 'Bhadrawati',
      status: 'ready',
      minPrice: 4500000,
      coverUrl: null,
    ),
    Project(
      id: 'pr4',
      name: 'Heritage Plaza',
      area: 'Ram Nagar',
      status: 'under_construction',
      minPrice: 6000000,
      coverUrl: null,
    ),
  ];

  static final leads = <Lead>[
    Lead(
      id: 'l1',
      propertyId: 'p2',
      propertyTitle: 'Lakefront Flats Phase 2',
      name: 'Ravi Sharma',
      phone: '9990001112',
      message: 'Interested in a site visit this weekend.',
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    Lead(
      id: 'l2',
      propertyId: 'p6',
      propertyTitle: 'Urban Heights 3 BHK',
      name: 'Nikita Rao',
      phone: '9990001113',
      message: 'Please share the brochure and floor plan.',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
    ),
  ];
}
